/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */

/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    Database: {
      database: string;
      host: string;
      password: string;
      port: number;
      type: 'sst.aws.Postgres';
      username: string;
    };
    DatabaseVPC: {
      type: 'sst.aws.Vpc';
    };
    FrontendSite: {
      type: 'sst.aws.StaticSite';
      url: string;
    };
    NestJSAPI: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
