/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const GithubWorkflowLazyRouteImport = createFileRoute('/githubWorkflow')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const InfraInfraIdLazyRouteImport = createFileRoute('/infra/$infraId')()
const JiraJiraIdLazyRouteImport = createFileRoute('/jira/$jiraId')()
const ProductsProductIdLazyRouteImport = createFileRoute(
  '/products/$productId',
)()
const SonarCloudSonarCloudIdLazyRouteImport = createFileRoute(
  '/sonarCloud/$sonarCloudId',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubWorkflowLazyRoute = GithubWorkflowLazyRouteImport.update({
  id: '/githubWorkflow',
  path: '/githubWorkflow',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/githubWorkflow.lazy').then((d) => d.Route),
)
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const InfraInfraIdLazyRoute = InfraInfraIdLazyRouteImport.update({
  id: '/infra/$infraId',
  path: '/infra/$infraId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/infra/$infraId.lazy').then((d) => d.Route),
)
const JiraJiraIdLazyRoute = JiraJiraIdLazyRouteImport.update({
  id: '/jira/$jiraId',
  path: '/jira/$jiraId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jira/$jiraId.lazy').then((d) => d.Route))
const ProductsProductIdLazyRoute = ProductsProductIdLazyRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/products/$productId.lazy').then((d) => d.Route),
)
const SonarCloudSonarCloudIdLazyRoute =
  SonarCloudSonarCloudIdLazyRouteImport.update({
    id: '/sonarCloud/$sonarCloudId',
    path: '/sonarCloud/$sonarCloudId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/sonarCloud/$sonarCloudId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/githubWorkflow': typeof GithubWorkflowLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/infra/$infraId': typeof InfraInfraIdLazyRoute
  '/jira/$jiraId': typeof JiraJiraIdLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/sonarCloud/$sonarCloudId': typeof SonarCloudSonarCloudIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/githubWorkflow': typeof GithubWorkflowLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/infra/$infraId': typeof InfraInfraIdLazyRoute
  '/jira/$jiraId': typeof JiraJiraIdLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/sonarCloud/$sonarCloudId': typeof SonarCloudSonarCloudIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/githubWorkflow': typeof GithubWorkflowLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/infra/$infraId': typeof InfraInfraIdLazyRoute
  '/jira/$jiraId': typeof JiraJiraIdLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/sonarCloud/$sonarCloudId': typeof SonarCloudSonarCloudIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/githubWorkflow'
    | '/settings'
    | '/infra/$infraId'
    | '/jira/$jiraId'
    | '/products/$productId'
    | '/sonarCloud/$sonarCloudId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/githubWorkflow'
    | '/settings'
    | '/infra/$infraId'
    | '/jira/$jiraId'
    | '/products/$productId'
    | '/sonarCloud/$sonarCloudId'
  id:
    | '__root__'
    | '/'
    | '/githubWorkflow'
    | '/settings'
    | '/infra/$infraId'
    | '/jira/$jiraId'
    | '/products/$productId'
    | '/sonarCloud/$sonarCloudId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GithubWorkflowLazyRoute: typeof GithubWorkflowLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  InfraInfraIdLazyRoute: typeof InfraInfraIdLazyRoute
  JiraJiraIdLazyRoute: typeof JiraJiraIdLazyRoute
  ProductsProductIdLazyRoute: typeof ProductsProductIdLazyRoute
  SonarCloudSonarCloudIdLazyRoute: typeof SonarCloudSonarCloudIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/githubWorkflow': {
      id: '/githubWorkflow'
      path: '/githubWorkflow'
      fullPath: '/githubWorkflow'
      preLoaderRoute: typeof GithubWorkflowLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infra/$infraId': {
      id: '/infra/$infraId'
      path: '/infra/$infraId'
      fullPath: '/infra/$infraId'
      preLoaderRoute: typeof InfraInfraIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira/$jiraId': {
      id: '/jira/$jiraId'
      path: '/jira/$jiraId'
      fullPath: '/jira/$jiraId'
      preLoaderRoute: typeof JiraJiraIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonarCloud/$sonarCloudId': {
      id: '/sonarCloud/$sonarCloudId'
      path: '/sonarCloud/$sonarCloudId'
      fullPath: '/sonarCloud/$sonarCloudId'
      preLoaderRoute: typeof SonarCloudSonarCloudIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GithubWorkflowLazyRoute: GithubWorkflowLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  InfraInfraIdLazyRoute: InfraInfraIdLazyRoute,
  JiraJiraIdLazyRoute: JiraJiraIdLazyRoute,
  ProductsProductIdLazyRoute: ProductsProductIdLazyRoute,
  SonarCloudSonarCloudIdLazyRoute: SonarCloudSonarCloudIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
